name: Deploy a Kubeflow Pipeline on GKE.
description: Compile, deploy and run a Kubeflow Pipeline on GKE.
author: albert-cintas-pot
inputs:
  kubeflow_url:
    description: The endpoint where your Kubeflow UI is running. 
    required: true
  pipeline_file_path:
    description: |
      The full path to pipeline.py file.
      This is provided by a Matrix by the Github Action. Pipelines must be stored inside the /pipelines folder
    required: true
  client_id:
    description: The IAP client id, which was specified when the kubeflow deployment where setup using IAP.
    required: true
  other_client_id:
    description: The other IAP client id, configured to be used for Desktop app authentication.
    required: true
  other_client_secret:
    description: The other IAP client secret.
    required: true
outputs:
  pipeline_name:
    description: The name of the pipeline submitted.
branding:
  color: 'blue'
  icon: 'upload-cloud'
runs:
  using: 'docker'
  image: 'docker://europe-west1-docker.pkg.dev/pot-test-environment/pot-kubeflow-poc/kfp-sdk:latest'
