name: Compile, Deploy and Run pipelines on Kubeflow

on:
  release:
    types: 
      - published

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*v})

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key # Not an actual user
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push
        id: docker_build_mlops
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: europe-west1-docker.pkg.dev/pot-test-environment/pot-kubeflow-poc/kfp-sdk:${{ steps.get_version.outputs.VERSION }},europe-west1-docker.pkg.dev/pot-test-environment/pot-kubeflow-poc/kfp-sdk:latest